apiVersion: v1
kind: Pod
metadata:
  name: backend-pagination-pg
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:16
      args:
        - postgres
        - -c
        - shared_preload_libraries=pg_stat_statements
        - -c
        - track_io_timing=on
        - -c
        - pg_stat_statements.track=all
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: books
      ports:
        - containerPort: 5432
          hostPort: 5432
